services:

    anicroche:
        volumes:
            - ./anicroche/avec.js:/app/avec.js
            - ./anicroche/adn:/app/adn

    apicroche:
        command: npm run dev
        volumes:
            - ./apicroche/sans.js:/app/sans.js
            - ./apicroche/adn:/app/adn
