services:

    anicroche:
        build: ./anicroche
        container_name: anicroche
        ports:
            - "4030:4030"
        environment:
            - PORT=4030

    apicroche:
        build: ./apicroche
        container_name: apicroche
        ports:
            - "5030:5030"
        environment:
            - PORT=5030
        volumes:
            - ./apicroche/depot:/app/depot
